import React, { useEffect, useState } from "react";
import { Check, Loader2, RefreshCw, Trash2, Upload } from "lucide-react";
import { cloudinaryConfig, uploadToCloudinary } from "../../../config/cloudinary";

const imageUrl = (image) => `https://res.cloudinary.com/${cloudinaryConfig.cloudName}/image/upload/v${image.version}/${image.public_id}.${image.format}`;
const MediaLibrary = () => {
  const [images, setImages] = useState([]); const [selected, setSelected] = useState(new Set()); const [loading, setLoading] = useState(false); const [uploading, setUploading] = useState(false); const [deleting, setDeleting] = useState(false); const [message, setMessage] = useState("");
  const refresh = async () => { setLoading(true); setMessage(""); try { const response = await fetch(`https://res.cloudinary.com/${cloudinaryConfig.cloudName}/image/list/${cloudinaryConfig.galleryTag}.json`); if (response.ok) setImages((await response.json()).resources || []); else if (response.status === 404) setImages([]); else setMessage("Cloudinary resource listing is not enabled. Enable Client-side resource listing in Cloudinary Security settings."); } catch { setMessage("Unable to load the Cloudinary gallery."); } finally { setLoading(false); } };
  useEffect(() => { refresh(); }, []);
  const upload = async (event) => { const files = Array.from(event.target.files || []); if (!files.length) return; setUploading(true); setMessage(""); try { await Promise.all(files.map(uploadToCloudinary)); setMessage(`${files.length} file(s) uploaded successfully.`); await refresh(); } catch (error) { setMessage(error?.message || "Upload failed."); } finally { setUploading(false); event.target.value = ""; } };
  const toggle = (id) => setSelected((current) => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next; });
  const deleteSelected = async () => { const assets = images.filter((image) => selected.has(image.public_id)).map((image) => ({ publicId: image.public_id, resourceType: image.resource_type || "image" })); if (!assets.length || !window.confirm(`Permanently remove ${assets.length} selected media file(s) from Cloudinary?`)) return; setDeleting(true); setMessage(""); try { const response = await fetch("/api/cloudinary/delete", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ assets }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to delete selected media."); setSelected(new Set()); setMessage(`${data.deleted || assets.length} media file(s) deleted permanently.`); await refresh(); } catch (error) { setMessage(error?.message || "Unable to delete selected media."); } finally { setDeleting(false); } };
  return <div className="space-y-6"><section className="rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-lg font-bold text-slate-900">Upload Media</h2><p className="mt-1 text-sm text-slate-500">Add new images to your Cloudinary gallery.</p></div><label className={`inline-flex cursor-pointer items-center gap-2 rounded-xl bg-[#b13896] px-5 py-2.5 text-sm font-bold text-white ${uploading ? "opacity-50" : ""}`}><Upload size={16}/>{uploading ? "Uploading..." : "Select Images"}<input type="file" multiple accept="image/*" onChange={upload} disabled={uploading} className="hidden"/></label></div>{message && <p className="mt-4 rounded-lg bg-slate-50 p-3 text-xs text-slate-600">{message}</p>}</section><section className="min-h-[400px] rounded-2xl border border-slate-100 bg-white p-6 shadow-sm"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold text-slate-900">Cloudinary Gallery</h2><p className="mt-1 text-xs text-slate-500">Select multiple images, then permanently delete them together.</p></div><div className="flex gap-2"><button onClick={refresh} title="Refresh gallery" className="rounded-lg border border-slate-200 p-2 text-slate-500"><RefreshCw size={16} className={loading ? "animate-spin" : ""}/></button><button disabled={!selected.size || deleting} onClick={deleteSelected} className="inline-flex items-center gap-2 rounded-lg bg-red-600 px-3 py-2 text-xs font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40"><Trash2 size={15}/>{deleting ? "Deleting..." : `Delete selected (${selected.size})`}</button></div></div>{loading ? <div className="grid h-64 place-items-center"><Loader2 className="animate-spin text-[#b13896]"/></div> : !images.length ? <div className="grid h-64 place-items-center text-sm text-slate-400">No images found in gallery.</div> : <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5">{images.map((image) => { const active = selected.has(image.public_id); return <button type="button" key={image.public_id} onClick={() => toggle(image.public_id)} className={`group relative aspect-square overflow-hidden rounded-xl border-2 text-left ${active ? "border-[#b13896]" : "border-transparent"}`}><img src={imageUrl(image)} alt={image.public_id} className="h-full w-full object-cover" loading="lazy"/><span className={`absolute left-2 top-2 grid h-5 w-5 place-items-center rounded-full ${active ? "bg-[#b13896] text-white" : "bg-white/90 text-transparent"}`}><Check size={13}/></span><span className="absolute inset-x-0 bottom-0 truncate bg-slate-950/60 px-2 py-1 text-[14px] text-white">{image.public_id.split("/").pop()}</span></button>; })}</div>}</section></div>;
};
export default MediaLibrary;
